--Pls Donate Im The Only Slave Here :(

local ScreenGui = Instance.new("ScreenGui")
local MainFrame = Instance.new("Frame")
local UICorner = Instance.new("UICorner")
local Ms2 = Instance.new("TextButton")
local UICorner_2 = Instance.new("UICorner")
local BedWars = Instance.new("TextButton")
local UICorner_3 = Instance.new("UICorner")
local Universal = Instance.new("TextButton")
local UICorner_4 = Instance.new("UICorner")
local JailBreak = Instance.new("TextButton")
local UICorner_5 = Instance.new("UICorner")
local PSX = Instance.new("TextButton")
local UICorner_6 = Instance.new("UICorner")
local Soon = Instance.new("TextButton")
local UICorner_7 = Instance.new("UICorner")
local Close = Instance.new("TextButton")
local UICorner_8 = Instance.new("UICorner")
local Minimize = Instance.new("TextButton")
local UICorner_9 = Instance.new("UICorner")
local TextLabel = Instance.new("TextLabel")
local UICorner_10 = Instance.new("UICorner")
local Start = Instance.new("Frame")
local UICorner_11 = Instance.new("UICorner")
local Opensh = Instance.new("TextButton")
local UICorner_12 = Instance.new("UICorner")
local Discord = Instance.new("TextButton")
local UICorner_13 = Instance.new("UICorner")
local TextLabel_2 = Instance.new("TextLabel")
local UICorner_14 = Instance.new("UICorner")
local TextLabel_3 = Instance.new("TextLabel")
local UICorner_15 = Instance.new("UICorner")
local UniversalFrame = Instance.new("Frame")
local TextLabel_4 = Instance.new("TextLabel")
local UICorner_16 = Instance.new("UICorner")
local ScrollingFrame = Instance.new("ScrollingFrame")
local ImageLabel = Instance.new("ImageLabel")
local UICorner_17 = Instance.new("UICorner")
local ExecuteSolaris = Instance.new("TextButton")
local UICorner_18 = Instance.new("UICorner")
local ImageLabel_2 = Instance.new("ImageLabel")
local UICorner_19 = Instance.new("UICorner")
local ExecuteDarkHub = Instance.new("TextButton")
local UICorner_20 = Instance.new("UICorner")
local ImageLabel_3 = Instance.new("ImageLabel")
local UICorner_21 = Instance.new("UICorner")
local ExecuteEvoV2 = Instance.new("TextButton")
local UICorner_22 = Instance.new("UICorner")
local ImageLabel_4 = Instance.new("ImageLabel")
local UICorner_23 = Instance.new("UICorner")
local ExecuteVestra = Instance.new("TextButton")
local UICorner_24 = Instance.new("UICorner")
local ImageLabel_5 = Instance.new("ImageLabel")
local UICorner_25 = Instance.new("UICorner")
local ExecuteVGHub = Instance.new("TextButton")
local UICorner_26 = Instance.new("UICorner")
local ImageLabel_6 = Instance.new("ImageLabel")
local UICorner_27 = Instance.new("UICorner")
local ExecuteStrawHooks = Instance.new("TextButton")
local UICorner_28 = Instance.new("UICorner")
local ImageLabel_7 = Instance.new("ImageLabel")
local UICorner_29 = Instance.new("UICorner")
local ImageLabel_8 = Instance.new("ImageLabel")
local UICorner_30 = Instance.new("UICorner")
local ExecuteBoltsHub = Instance.new("TextButton")
local UICorner_31 = Instance.new("UICorner")
local ExecuteZyrexHub = Instance.new("TextButton")
local UICorner_32 = Instance.new("UICorner")
local ImageLabel_9 = Instance.new("ImageLabel")
local UICorner_33 = Instance.new("UICorner")
local ExecuteKebabHub = Instance.new("TextButton")
local UICorner_34 = Instance.new("UICorner")
local ImageLabel_10 = Instance.new("ImageLabel")
local UICorner_35 = Instance.new("UICorner")
local ExecuteParvusHub = Instance.new("TextButton")
local UICorner_36 = Instance.new("UICorner")
local ImageLabel_11 = Instance.new("ImageLabel")
local UICorner_37 = Instance.new("UICorner")
local ImageLabel_12 = Instance.new("ImageLabel")
local UICorner_38 = Instance.new("UICorner")
local ImageLabel_13 = Instance.new("ImageLabel")
local UICorner_39 = Instance.new("UICorner")
local ImageLabel_14 = Instance.new("ImageLabel")
local UICorner_40 = Instance.new("UICorner")
local ImageLabel_15 = Instance.new("ImageLabel")
local UICorner_41 = Instance.new("UICorner")
local ImageLabel_16 = Instance.new("ImageLabel")
local UICorner_42 = Instance.new("UICorner")
local ExecuteOwlHub = Instance.new("TextButton")
local UICorner_43 = Instance.new("UICorner")
local ExecuteSorkyHub = Instance.new("TextButton")
local UICorner_44 = Instance.new("UICorner")
local ExecuteMonkeHub = Instance.new("TextButton")
local UICorner_45 = Instance.new("UICorner")
local ExecuteStefan = Instance.new("TextButton")
local UICorner_46 = Instance.new("UICorner")
local ExecuteStefan_2 = Instance.new("TextButton")
local UICorner_47 = Instance.new("UICorner")
local ExecuteZephyrX = Instance.new("TextButton")
local UICorner_48 = Instance.new("UICorner")
local ExecuteSirius = Instance.new("TextButton")
local UICorner_49 = Instance.new("UICorner")
local TextLabel_5 = Instance.new("TextLabel")
local UICorner_50 = Instance.new("UICorner")
local Close_2 = Instance.new("TextButton")
local UICorner_51 = Instance.new("UICorner")
local Minimize_2 = Instance.new("TextButton")
local UICorner_52 = Instance.new("UICorner")
local BedWarsFrame = Instance.new("Frame")
local TextLabel_6 = Instance.new("TextLabel")
local UICorner_53 = Instance.new("UICorner")
local ScrollingFrame_2 = Instance.new("ScrollingFrame")
local ImageLabel_17 = Instance.new("ImageLabel")
local UICorner_54 = Instance.new("UICorner")
local ExecuteVape = Instance.new("TextButton")
local UICorner_55 = Instance.new("UICorner")
local ImageLabel_18 = Instance.new("ImageLabel")
local UICorner_56 = Instance.new("UICorner")
local ExecuteEngoWare = Instance.new("TextButton")
local UICorner_57 = Instance.new("UICorner")
local ImageLabel_19 = Instance.new("ImageLabel")
local UICorner_58 = Instance.new("UICorner")
local ExecuteRekt = Instance.new("TextButton")
local UICorner_59 = Instance.new("UICorner")
local ImageLabel_20 = Instance.new("ImageLabel")
local UICorner_60 = Instance.new("UICorner")
local ExecuteNoboline = Instance.new("TextButton")
local UICorner_61 = Instance.new("UICorner")
local TextLabel_7 = Instance.new("TextLabel")
local UICorner_62 = Instance.new("UICorner")
local Close_3 = Instance.new("TextButton")
local UICorner_63 = Instance.new("UICorner")
local Minimize_3 = Instance.new("TextButton")
local UICorner_64 = Instance.new("UICorner")
local MS2Frame = Instance.new("Frame")
local TextLabel_8 = Instance.new("TextLabel")
local UICorner_65 = Instance.new("UICorner")
local ScrollingFrame_3 = Instance.new("ScrollingFrame")
local ImageLabel_21 = Instance.new("ImageLabel")
local UICorner_66 = Instance.new("UICorner")
local ExecuteZeerox = Instance.new("TextButton")
local UICorner_67 = Instance.new("UICorner")
local ImageLabel_22 = Instance.new("ImageLabel")
local UICorner_68 = Instance.new("UICorner")
local ExecuteExodus = Instance.new("TextButton")
local UICorner_69 = Instance.new("UICorner")
local ImageLabel_23 = Instance.new("ImageLabel")
local UICorner_70 = Instance.new("UICorner")
local ExecuteKelp = Instance.new("TextButton")
local UICorner_71 = Instance.new("UICorner")
local ImageLabel_24 = Instance.new("ImageLabel")
local UICorner_72 = Instance.new("UICorner")
local ExecuteVestra_2 = Instance.new("TextButton")
local UICorner_73 = Instance.new("UICorner")
local ImageLabel_25 = Instance.new("ImageLabel")
local UICorner_74 = Instance.new("UICorner")
local ExecuteSaza = Instance.new("TextButton")
local UICorner_75 = Instance.new("UICorner")
local ImageLabel_26 = Instance.new("ImageLabel")
local UICorner_76 = Instance.new("UICorner")
local ExecuteSoggyWare = Instance.new("TextButton")
local UICorner_77 = Instance.new("UICorner")
local ImageLabel_27 = Instance.new("ImageLabel")
local UICorner_78 = Instance.new("UICorner")
local ImageLabel_28 = Instance.new("ImageLabel")
local UICorner_79 = Instance.new("UICorner")
local ExecuteExtremeHub = Instance.new("TextButton")
local UICorner_80 = Instance.new("UICorner")
local ExecutePhantomHub = Instance.new("TextButton")
local UICorner_81 = Instance.new("UICorner")
local TextLabel_9 = Instance.new("TextLabel")
local UICorner_82 = Instance.new("UICorner")
local Close_4 = Instance.new("TextButton")
local UICorner_83 = Instance.new("UICorner")
local Minimize_4 = Instance.new("TextButton")
local UICorner_84 = Instance.new("UICorner")
local UITOGGLERFrame = Instance.new("Frame")
local UICorner_85 = Instance.new("UICorner")
local OpensTheFrame = Instance.new("TextButton")
local UICorner_86 = Instance.new("UICorner")

--Properties:

ScreenGui.Parent = game.CoreGui

MainFrame.Name = "Main Frame"
MainFrame.Parent = ScreenGui
MainFrame.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
MainFrame.Position = UDim2.new(0.408794791, 0, 0.240325585, 0)
MainFrame.Size = UDim2.new(0, 312, 0, 372)
MainFrame.Visible = false
MainFrame.Active = true
MainFrame.Draggable = true

UICorner.Parent = MainFrame

Ms2.Name = "Ms2"
Ms2.Parent = MainFrame
Ms2.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
Ms2.Position = UDim2.new(0.0612092614, 0, 0.190860212, 0)
Ms2.Size = UDim2.new(0, 273, 0, 37)
Ms2.Font = Enum.Font.SourceSans
Ms2.Text = "Mining SImulator 2"
Ms2.TextColor3 = Color3.fromRGB(4, 91, 2)
Ms2.TextSize = 28.000
Ms2.MouseButton1Down:connect(function()
	MainFrame.Visible = false
	wait(0.4)
	loadstring(game:HttpGet("https://raw.githubusercontent.com/Fixyz1/MS2/main/MS2%20HACKS/.Lua",true))()
end)

UICorner_2.Parent = Ms2

BedWars.Name = "BedWars"
BedWars.Parent = MainFrame
BedWars.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
BedWars.Position = UDim2.new(0.0676195174, 0, 0.330645144, 0)
BedWars.Size = UDim2.new(0, 273, 0, 37)
BedWars.Font = Enum.Font.SourceSans
BedWars.Text = "BedWars"
BedWars.TextColor3 = Color3.fromRGB(4, 91, 2)
BedWars.TextSize = 28.000
BedWars.MouseButton1Down:connect(function()
	MainFrame.Visible = false
	wait(0.4)
	loadstring(game:HttpGet("https://raw.githubusercontent.com/Fixyz1/BEDWARS-HACKER/main/Tree/BOOBIES/.Lua",true))()
end)

UICorner_3.Parent = BedWars

Universal.Name = "Universal"
Universal.Parent = MainFrame
Universal.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
Universal.Position = UDim2.new(0.0676195174, 0, 0.44892472, 0)
Universal.Size = UDim2.new(0, 273, 0, 37)
Universal.Font = Enum.Font.SourceSans
Universal.Text = "Universal / Shooter Games"
Universal.TextColor3 = Color3.fromRGB(4, 91, 2)
Universal.TextSize = 28.000
Universal.MouseButton1Down:connect(function()
	MainFrame.Visible = false
	wait(0.4)
	loadstring(game:HttpGet("https://raw.githubusercontent.com/Fixyz1/A-New-Private-Script/main/Universal%20Script",true))()
end)

UICorner_4.Parent = Universal

JailBreak.Name = "JailBreak"
JailBreak.Parent = MainFrame
JailBreak.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
JailBreak.Position = UDim2.new(0.0676195025, 0, 0.720430076, 0)
JailBreak.Size = UDim2.new(0, 273, 0, 37)
JailBreak.Font = Enum.Font.SourceSans
JailBreak.Text = "JailBreak / Soon"
JailBreak.TextColor3 = Color3.fromRGB(4, 91, 2)
JailBreak.TextSize = 28.000

UICorner_5.Parent = JailBreak

PSX.Name = "PSX"
PSX.Parent = MainFrame
PSX.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
PSX.Position = UDim2.new(0.0676195174, 0, 0.588709712, 0)
PSX.Size = UDim2.new(0, 273, 0, 37)
PSX.Font = Enum.Font.SourceSans
PSX.Text = "Pet Simulator X / Soon"
PSX.TextColor3 = Color3.fromRGB(4, 91, 2)
PSX.TextSize = 28.000

UICorner_6.Parent = PSX

Soon.Name = "Soon"
Soon.Parent = MainFrame
Soon.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
Soon.Position = UDim2.new(0.0580041334, 0, 0.860214949, 0)
Soon.Size = UDim2.new(0, 273, 0, 37)
Soon.Font = Enum.Font.SourceSans
Soon.Text = "Soon"
Soon.TextColor3 = Color3.fromRGB(4, 91, 2)
Soon.TextSize = 28.000

UICorner_7.Parent = Soon

Close.Name = "Close"
Close.Parent = MainFrame
Close.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
Close.Position = UDim2.new(0.820824623, 0, 0, 0)
Close.Size = UDim2.new(0, 55, 0, 34)
Close.Font = Enum.Font.SourceSans
Close.Text = "X"
Close.TextColor3 = Color3.fromRGB(4, 91, 2)
Close.TextSize = 36.000
Close.MouseButton1Down:connect(function()
	MainFrame.Visible = false
end)

UICorner_8.Parent = Close

Minimize.Name = "Minimize"
Minimize.Parent = MainFrame
Minimize.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
Minimize.Position = UDim2.new(0.644542575, 0, 0, 0)
Minimize.Size = UDim2.new(0, 55, 0, 34)
Minimize.Font = Enum.Font.SourceSans
Minimize.Text = "-"
Minimize.TextColor3 = Color3.fromRGB(4, 91, 2)
Minimize.TextSize = 48.000
Minimize.MouseButton1Down:connect(function()
	UITOGGLERFrame.Visible = true
	MainFrame.Visible = false
end)

UICorner_9.Parent = Minimize

TextLabel.Parent = MainFrame
TextLabel.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
TextLabel.Size = UDim2.new(0, 201, 0, 34)
TextLabel.Font = Enum.Font.SourceSans
TextLabel.Text = "Spotify Hub X"
TextLabel.TextColor3 = Color3.fromRGB(0, 100, 56)
TextLabel.TextSize = 18.000

UICorner_10.Parent = TextLabel

Start.Name = "Start"
Start.Parent = ScreenGui
Start.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
Start.Position = UDim2.new(0.377035797, 0, 0.306605726, 0)
Start.Size = UDim2.new(0, 376, 0, 216)
Start.Visible = true
Start.Active = true

UICorner_11.Parent = Start

Opensh.Name = "Open sh"
Opensh.Parent = Start
Opensh.BackgroundColor3 = Color3.fromRGB(0, 104, 5)
Opensh.Position = UDim2.new(0.099433735, 0, 0.583333373, 0)
Opensh.Size = UDim2.new(0, 301, 0, 64)
Opensh.Font = Enum.Font.SourceSans
Opensh.Text = "Open Spotify Hub X"
Opensh.TextColor3 = Color3.fromRGB(0, 0, 0)
Opensh.TextSize = 28.000
Opensh.MouseButton1Down:connect(function()
	Start.Visible = false
	wait(0.4)
	MainFrame.Visible = true
end)

UICorner_12.Parent = Opensh

Discord.Name = "Discord"
Discord.Parent = Start
Discord.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
Discord.Position = UDim2.new(-0.000772192143, 0, 0, 0)
Discord.Size = UDim2.new(0, 240, 0, 52)
Discord.Font = Enum.Font.SourceSans
Discord.Text = "Discord Server"
Discord.TextColor3 = Color3.fromRGB(0, 104, 5)
Discord.TextSize = 28.000
Discord.MouseButton1Down:connect(function()
	setclipboard("https://discord.gg/9PKn8g8W")
end)

UICorner_13.Parent = Discord

TextLabel_2.Parent = Start
TextLabel_2.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
TextLabel_2.Position = UDim2.new(0.635638297, 0, 0.00925925933, 0)
TextLabel_2.Size = UDim2.new(0, 137, 0, 50)
TextLabel_2.Font = Enum.Font.SourceSans
TextLabel_2.Text = "V1.0.1"
TextLabel_2.TextColor3 = Color3.fromRGB(0, 104, 5)
TextLabel_2.TextSize = 22.000

UICorner_14.Parent = TextLabel_2

TextLabel_3.Parent = Start
TextLabel_3.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
TextLabel_3.Position = UDim2.new(0.135638297, 0, 0.402777791, 0)
TextLabel_3.Size = UDim2.new(0, 273, 0, 39)
TextLabel_3.Font = Enum.Font.SourceSans
TextLabel_3.Text = "Reminder:These Scripts Are Safe & Unbannable Unless Trey're Patched!!"
TextLabel_3.TextColor3 = Color3.fromRGB(0, 104, 5)
TextLabel_3.TextSize = 14.000

UICorner_15.Parent = TextLabel_3

UITOGGLERFrame.Name = "UI TOGGLER Frame"
UITOGGLERFrame.Parent = ScreenGui
UITOGGLERFrame.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
UITOGGLERFrame.Position = UDim2.new(0.504071712, 0, 0.0417827293, 0)
UITOGGLERFrame.Size = UDim2.new(0, 80, 0, 53)
UITOGGLERFrame.Visible = false
UITOGGLERFrame.Active = true
UITOGGLERFrame.Draggable = true

UICorner_85.Parent = UITOGGLERFrame

OpensTheFrame.Name = "Opens The Frame"
OpensTheFrame.Parent = UITOGGLERFrame
OpensTheFrame.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
OpensTheFrame.Position = UDim2.new(-0.00416636467, 0, 0, 0)
OpensTheFrame.Size = UDim2.new(0, 80, 0, 53)
OpensTheFrame.Font = Enum.Font.SourceSans
OpensTheFrame.Text = "Toggle ME"
OpensTheFrame.TextColor3 = Color3.fromRGB(0, 100, 55)
OpensTheFrame.TextSize = 14.000
OpensTheFrame.MouseButton1Down:Connect(function()
UITOGGLERFrame.Visible = false
	MainFrame.Visible = true
end)

UICorner_86.Parent = OpensTheFrame
