-- Hacked In!!

local ScreenGui = Instance.new("ScreenGui")
local MainFrame = Instance.new("Frame")
local UICorner = Instance.new("UICorner")
local MiningSimulator2 = Instance.new("TextButton")
local UICorner_2 = Instance.new("UICorner")
local BedWars = Instance.new("TextButton")
local UICorner_3 = Instance.new("UICorner")
local Universal = Instance.new("TextButton")
local UICorner_4 = Instance.new("UICorner")
local ClickerSimulatorSoon = Instance.new("TextButton")
local UICorner_5 = Instance.new("UICorner")
local PetSimulatorX = Instance.new("TextButton")
local UICorner_6 = Instance.new("UICorner")
local Close = Instance.new("TextButton")
local UICorner_7 = Instance.new("UICorner")
local Minimize = Instance.new("TextButton")
local UICorner_8 = Instance.new("UICorner")
local TextLabel = Instance.new("TextLabel")
local UICorner_9 = Instance.new("UICorner")
local DevV4Private = Instance.new("TextButton")
local UICorner_10 = Instance.new("UICorner")
local PowerSoftware = Instance.new("TextButton")
local UICorner_11 = Instance.new("UICorner")
local Discord = Instance.new("TextButton")
local UICorner_12 = Instance.new("UICorner")
local UITOGGLERFrame = Instance.new("Frame")
local UICorner_13 = Instance.new("UICorner")
local OpensTheFrame = Instance.new("TextButton")
local UICorner_14 = Instance.new("UICorner")

--Properties:

ScreenGui.Parent = game.CoreGui

MainFrame.Name = "Main Frame"
MainFrame.Parent = ScreenGui
MainFrame.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
MainFrame.Position = UDim2.new(0.283387691, 0, 0.212470442, 0)
MainFrame.Size = UDim2.new(0, 528, 0, 303)
MainFrame.Visible = false
MainFrame.Active = true
MainFrame.Draggable = true

UICorner.Parent = MainFrame

MiningSimulator2.Name = "Mining Simulator 2"
MiningSimulator2.Parent = MainFrame
MiningSimulator2.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
MiningSimulator2.Position = UDim2.new(0.0346940979, 0, 0.161290318, 0)
MiningSimulator2.Size = UDim2.new(0, 258, 0, 37)
MiningSimulator2.Font = Enum.Font.SourceSans
MiningSimulator2.Text = "Mining Simulator 2"
MiningSimulator2.TextColor3 = Color3.fromRGB(255, 255, 255)
MiningSimulator2.TextSize = 28.000
MiningSimulator2.MouseButton1Down:connect(function()
	MainFrame.Visible = false
	wait(0.4)
	loadstring(game:HttpGet("https://raw.githubusercontent.com/JustAfkHatch/MS2/main/New-Update!/.Lua",true))()
end)

UICorner_2.Parent = MiningSimulator2

BedWars.Name = "BedWars"
BedWars.Parent = MainFrame
BedWars.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
BedWars.Position = UDim2.new(0.0354225487, 0, 0.323325872, 0)
BedWars.Size = UDim2.new(0, 273, 0, 37)
BedWars.Font = Enum.Font.SourceSans
BedWars.Text = "BedWars"
BedWars.TextColor3 = Color3.fromRGB(255, 255, 255)
BedWars.TextSize = 28.000
BedWars.MouseButton1Down:connect(function()
	MainFrame.Visible = false
	wait(0.4)
	loadstring(game:HttpGet("https://raw.githubusercontent.com/JustAfkHatch/BedWars/main/New-Frame/Update/.Lua",true))()
end)

UICorner_3.Parent = BedWars

Universal.Name = "Universal"
Universal.Parent = MainFrame
Universal.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
Universal.Position = UDim2.new(0.0354225487, 0, 0.493425936, 0)
Universal.Size = UDim2.new(0, 273, 0, 37)
Universal.Font = Enum.Font.SourceSans
Universal.Text = "Universal / Shooter Games"
Universal.TextColor3 = Color3.fromRGB(255, 255, 255)
Universal.TextSize = 28.000
Universal.MouseButton1Down:connect(function()
	MainFrame.Visible = false
	wait(0.4)
	loadstring(game:HttpGet("https://raw.githubusercontent.com/JustAfkHatch/Universal/main/Script-Hehe/.Lua",true))()
end)

UICorner_4.Parent = Universal

ClickerSimulatorSoon.Name = "Clicker Simulator / Soon"
ClickerSimulatorSoon.Parent = MainFrame
ClickerSimulatorSoon.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
ClickerSimulatorSoon.Position = UDim2.new(0.0335285962, 0, 0.825428486, 0)
ClickerSimulatorSoon.Size = UDim2.new(0, 273, 0, 37)
ClickerSimulatorSoon.Font = Enum.Font.SourceSans
ClickerSimulatorSoon.Text = "Clicker Simulator / Soon"
ClickerSimulatorSoon.TextColor3 = Color3.fromRGB(255, 255, 255)
ClickerSimulatorSoon.TextSize = 28.000

UICorner_5.Parent = ClickerSimulatorSoon

PetSimulatorX.Name = "Pet Simulator X"
PetSimulatorX.Parent = MainFrame
PetSimulatorX.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
PetSimulatorX.Position = UDim2.new(0.0354225487, 0, 0.65838927, 0)
PetSimulatorX.Size = UDim2.new(0, 273, 0, 37)
PetSimulatorX.Font = Enum.Font.SourceSans
PetSimulatorX.Text = "Pet Simulator X"
PetSimulatorX.TextColor3 = Color3.fromRGB(255, 255, 255)
PetSimulatorX.TextSize = 28.000
PetSimulatorX.MouseButton1Down:connect(function()
	MainFrame.Visible = false
	wait(0.4)
	loadstring(game:HttpGet("https://raw.githubusercontent.com/JustAfkHatch/Pet-Sim-X/Roblox_Script/.Lua",true))()
end)

UICorner_6.Parent = PetSimulatorX

Close.Name = "Close"
Close.Parent = MainFrame
Close.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
Close.Position = UDim2.new(0.894688249, 0, 0, 0)
Close.Size = UDim2.new(0, 55, 0, 34)
Close.Font = Enum.Font.SourceSans
Close.Text = "X"
Close.TextColor3 = Color3.fromRGB(255, 255, 255)
Close.TextSize = 36.000
Close.MouseButton1Down:connect(function()
	MainFrame.Visible = false
end)

UICorner_7.Parent = Close

Minimize.Name = "Minimize"
Minimize.Parent = MainFrame
Minimize.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
Minimize.Position = UDim2.new(0.790375888, 0, 0, 0)
Minimize.Size = UDim2.new(0, 55, 0, 34)
Minimize.Font = Enum.Font.SourceSans
Minimize.Text = "-"
Minimize.TextColor3 = Color3.fromRGB(255, 255, 255)
Minimize.TextSize = 48.000
Minimize.MouseButton1Down:connect(function()
	MainFrame.Visible = false
	UITOGGLERFrame.Visible = true
end)

UICorner_8.Parent = Minimize

TextLabel.Parent = MainFrame
TextLabel.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
TextLabel.Size = UDim2.new(0, 417, 0, 34)
TextLabel.Font = Enum.Font.SourceSans
TextLabel.Text = "Dev V4 Lua"
TextLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
TextLabel.TextSize = 36.000

UICorner_9.Parent = TextLabel

DevV4Private.Name = "Dev V4 Private"
DevV4Private.Parent = MainFrame
DevV4Private.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
DevV4Private.Position = UDim2.new(0.578254759, 0, 0.161290318, 0)
DevV4Private.Size = UDim2.new(0, 205, 0, 37)
DevV4Private.Font = Enum.Font.SourceSans
DevV4Private.Text = "Dev V4 Private"
DevV4Private.TextColor3 = Color3.fromRGB(255, 255, 255)
DevV4Private.TextSize = 28.000
DevV4Private.MouseButton1Down:connect(function()
	MainFrame.Visible = false
	wait(0.4)
	loadstring("\108\111\97\100\115\116\114\105\110\103\40\103\97\109\101\58\72\116\116\112\71\101\116\40\34\104\116\116\112\115\58\47\47\114\97\119\46\103\105\116\104\117\98\117\115\101\114\99\111\110\116\101\110\116\46\99\111\109\47\74\117\115\116\65\102\107\72\97\116\99\104\47\68\101\118\45\86\52\45\80\114\105\118\97\116\101\47\80\114\105\118\97\116\101\45\72\97\99\107\47\46\76\117\97\34\44\116\114\117\101\41\41\40\41\10")()
end)
	
UICorner_10.Parent = DevV4Private

PowerSoftware.Name = "Power Software"
PowerSoftware.Parent = MainFrame
PowerSoftware.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
PowerSoftware.Position = UDim2.new(0.578254759, 0, 0.320877284, 0)
PowerSoftware.Size = UDim2.new(0, 205, 0, 37)
PowerSoftware.Font = Enum.Font.SourceSans
PowerSoftware.Text = "Power Software"
PowerSoftware.TextColor3 = Color3.fromRGB(255, 255, 255)
PowerSoftware.TextSize = 28.000
PowerSoftware.MouseButton1Down:connect(function()
	MainFrame.Visible = false
	wait(0.4)
	loadstring(game:HttpGet("https://raw.githubusercontent.com/JustAfkHatch/Power-Software-V2/main/For-Roblox/OldMainScript/.Lua",true))()
end)
	
UICorner_11.Parent = PowerSoftware

Discord.Name = "Discord"
Discord.Parent = MainFrame
Discord.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
Discord.Position = UDim2.new(0.580148757, 0, 0, 0)
Discord.Size = UDim2.new(0, 111, 0, 27)
Discord.Font = Enum.Font.SourceSans
Discord.Text = "Discord Server"
Discord.TextColor3 = Color3.fromRGB(255, 255, 255)
Discord.TextSize = 16.000
Discord.MouseButton1Down:connect(function()
	setclipboard("https://discord.gg/4NrZVSpX")
end)

UICorner_12.Parent = Discord

UITOGGLERFrame.Name = "UI TOGGLER Frame"
UITOGGLERFrame.Parent = ScreenGui
UITOGGLERFrame.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
UITOGGLERFrame.Position = UDim2.new(0.467426747, 0, -0.0236768797, 0)
UITOGGLERFrame.Size = UDim2.new(0, 80, 0, 53)
UITOGGLERFrame.Active = true
UITOGGLERFrame.Draggable = true

UICorner_13.Parent = UITOGGLERFrame

OpensTheFrame.Name = "Opens The Frame"
OpensTheFrame.Parent = UITOGGLERFrame
OpensTheFrame.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
OpensTheFrame.Position = UDim2.new(-0.00416636467, 0, 0, 0)
OpensTheFrame.Size = UDim2.new(0, 80, 0, 53)
OpensTheFrame.Font = Enum.Font.SourceSans
OpensTheFrame.Text = "Toggle"
OpensTheFrame.TextColor3 = Color3.fromRGB(255, 255, 255)
OpensTheFrame.TextSize = 14.000
OpensTheFrame.MouseButton1Down:connect(function()
	UITOGGLERFrame.Visible = false
	MainFrame.Visible = true
end)

UICorner_14.Parent = OpensTheFrame
